### ISSUE TITLE
Fails using Ruby 2.1.2

### ISSUE THREAD

**Issue by DanielKehoe** [jlong/serve#118]
I successfully installed and ran serve under ruby 1.9.3p448.

Using Ruby 2.1.2, I get an an error:

```
$ ruby -v
ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-darwin13.0]
$ gem -v
2.2.2
$ serve
/Users/danielkehoe/.rvm/rubies/ruby-2.1.2/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- i18n/core_ext/string/interpolate (LoadError)
    from /Users/danielkehoe/.rvm/rubies/ruby-2.1.2/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/danielkehoe/.rvm/gems/ruby-2.1.2@serve/gems/activesupport-3.2.19/lib/active_support/core_ext/string/interpolation.rb:2:in `<top (required)>'
    from /Users/danielkehoe/.rvm/rubies/ruby-2.1.2/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/danielkehoe/.rvm/rubies/ruby-2.1.2/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/danielkehoe/.rvm/gems/ruby-2.1.2@serve/gems/activesupport-3.2.19/lib/active_support/core_ext/string.rb:9:in `<top (required)>'
    from /Users/danielkehoe/.rvm/rubies/ruby-2.1.2/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/danielkehoe/.rvm/rubies/ruby-2.1.2/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/danielkehoe/.rvm/gems/ruby-2.1.2@serve/gems/activesupport-3.2.19/lib/active_support/core_ext.rb:2:in `block in <top (required)>'
    from /Users/danielkehoe/.rvm/gems/ruby-2.1.2@serve/gems/activesupport-3.2.19/lib/active_support/core_ext.rb:1:in `each'
    from /Users/danielkehoe/.rvm/gems/ruby-2.1.2@serve/gems/activesupport-3.2.19/lib/active_support/core_ext.rb:1:in `<top (required)>'
    from /Users/danielkehoe/.rvm/rubies/ruby-2.1.2/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/danielkehoe/.rvm/rubies/ruby-2.1.2/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/danielkehoe/.rvm/gems/ruby-2.1.2@serve/gems/activesupport-3.2.19/lib/active_support/all.rb:3:in `<top (required)>'
    from /Users/danielkehoe/.rvm/rubies/ruby-2.1.2/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/danielkehoe/.rvm/rubies/ruby-2.1.2/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/danielkehoe/.rvm/gems/ruby-2.1.2@serve/gems/serve-1.5.2/lib/serve.rb:1:in `<top (required)>'
    from /Users/danielkehoe/.rvm/rubies/ruby-2.1.2/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/danielkehoe/.rvm/rubies/ruby-2.1.2/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/danielkehoe/.rvm/gems/ruby-2.1.2@serve/gems/serve-1.5.2/bin/serve:13:in `<top (required)>'
    from /Users/danielkehoe/.rvm/gems/ruby-2.1.2@serve/bin/serve:23:in `load'
    from /Users/danielkehoe/.rvm/gems/ruby-2.1.2@serve/bin/serve:23:in `<main>'
    from /Users/danielkehoe/.rvm/gems/ruby-2.1.2@serve/bin/ruby_executable_hooks:15:in `eval'
    from /Users

```

**Comment by wazery** [comment]
I can reproduce this on my machine, I will try to figure out what is the problem.
